/* Senthetic Dataset */
const arrayofDisease = [
"Abscess of skin",
"Acne vulgaris",
"Actinic keratosis",
"Acute bronchitis",
"Acute sinusitis",
"Adjustment disorder",
"Age-related macular degeneration",
"Allergic rhinitis",
"Alopecia areata",
"Anal fissure",
"Anxiety disorder",
"Appendicitis",
"Asthma",
"Atrial fibrillation",
"Benign prostatic hyperplasia",
"Bipolar disorder",
"Bronchiectasis",
"Bursitis",
"Carpal tunnel syndrome",
"Cataract",
"Cellulitis",
"Chronic kidney disease",
"Chronic obstructive pulmonary disease",
"Congestive heart failure",
"Constipation",
"Coronary artery disease",
"Crohn's disease",
"Cystitis",
"Dehydration",
"Dementia",
"Dental caries",
"Depression",
"Dermatitis",
"Diabetes mellitus type 1",
"Diabetes mellitus type 2",
"Diarrhea",
"Diverticulitis",
"Dry eye syndrome",
"Dyspepsia",
"Eczema",
"Endometriosis",
"Epididymitis",
"Esophagitis",
"Fibromyalgia",
"Folliculitis",
"Gallstones",
"Gastroenteritis",
"Gastroesophageal reflux disease",
"Gout",
"Headache",
"Hearing loss",
"Heartburn",
"Hemorrhoids",
"Herpes simplex",
"Herpes zoster",
"Hiatal hernia",
"Hyperlipidemia",
"Hypertension",
"Hypothyroidism",
"Impetigo",
"Influenza",
"Ingrown toenail",
"Insomnia",
"Irritable bowel syndrome",
"Laryngitis",
"Lumbago",
"Macular degeneration",
"Major depressive disorder",
"Melanoma",
"Ménière's disease",
"Migraine",
"Mitral valve prolapse",
"Multiple sclerosis",
"Muscle strain",
"Nasal polyps",
"Osteoarthritis",
"Osteoporosis",
"Otitis externa",
"Otitis media",
"Ovarian cyst",
"Panic disorder",
"Parkinson's disease",
"Peptic ulcer",
"Peripheral neuropathy",
"Pharyngitis",
"Plantar fasciitis",
"Pneumonia",
"Polycystic ovary syndrome",
"Post-traumatic stress disorder",
"Premenstrual syndrome",
"Prostatitis",
"Psoriasis",
"Pulmonary embolism",
"Pyelonephritis",
"Raynaud's phenomenon",
"Renal colic",
"Restless legs syndrome",
"Rheumatoid arthritis",
"Rosacea",
"Sciatica",
"Seborrheic dermatitis",
"Seasonal affective disorder",
"Shingles",
"Sinusitis",
"Sleep apnea",
"Social anxiety disorder",
"Spinal stenosis",
"Sprain",
"Stomach ulcer",
"Stroke",
"Tendonitis",
"Tinnitus",
"Tonsillitis",
"Ulcerative colitis",
"Urinary incontinence",
"Urinary tract infection",
"Urticaria",
"Varicose veins",
"Vertigo",
"Viral pharyngitis",
"Warts",
"Achilles tendinitis",
"Acute laryngitis",
"Adenoiditis",
"Alcoholic hepatitis",
"Allergic conjunctivitis",
"Amblyopia",
"Ankylosing spondylitis",
"Aortic stenosis",
"Aphthous ulcer",
"Bell's palsy",
"Blepharitis",
"Boil",
"Bunion",
"Chalazion",
"Cholecystitis",
"Colitis",
"Conjunctivitis",
"Costochondritis",
"Cubital tunnel syndrome",
"Deep vein thrombosis",
"Dupuytren's contracture",
"Ectropion",
"Entropion",
"Epicondylitis",
"Epilepsy",
"Fifth disease",
"Ganglion cyst",
"Glaucoma",
"Hallux valgus",
"Hashimoto's thyroiditis",
"Hyperthyroidism",
"Keratitis",
"Kyphosis",
"Lichen planus",
"Lordosis",
"Lupus erythematosus",
"Lymphangitis",
"Mastitis",
"Molluscum contagiosum",
"Myasthenia gravis",
"Myocardial infarction",
"Necrotizing fasciitis",
"Neuralgia",
"Optic neuritis",
"Oral thrush",
"Orchitis",
"Paget's disease of bone",
"Pancreatitis",
"Paronychia",
"Pericarditis",
"Pityriasis rosea",
"Pleural effusion",
"Pleurisy",
"Polymyalgia rheumatica",
"Posterior tibial tendon dysfunction",
"Preseptal cellulitis",
"Pseudogout",
"Pterygium",
"Retinal detachment",
"Rotator cuff tear",
"Sarcoidosis",
"Scleroderma",
"Scoliosis",
"Sjogren's syndrome",
"Staphylococcal scalded skin syndrome",
"Sty",
"Temporal arteritis",
"Tennis elbow",
"Thoracic outlet syndrome",
"Thrombophlebitis",
"Tinea corporis",
"Tinea cruris",
"Tinea pedis",
"Trigeminal neuralgia",
"Uveitis",
"Vasculitis",
"Vitiligo",
"Whiplash",
"Zoster sine herpete",
"Abdominal aortic aneurysm",
"Acalculous cholecystitis",
"Acute cholecystitis",
"Acute fatty liver of pregnancy",
"Acute glomerulonephritis",
"Acute interstitial nephritis",
"Acute liver failure",
"Acute mastoiditis",
"Acute necrotizing pancreatitis",
"Acute pericarditis",
"Acute pyelonephritis",
"Acute respiratory distress syndrome",
"Addison's disease",
"Adhesive capsulitis",
"Alcoholic cirrhosis",
"Allergic bronchopulmonary aspergillosis",
"Amebiasis",
"Amyloidosis",
"Anaphylaxis",
"Angina pectoris",
"Anterior uveitis",
"Aplastic anemia",
"Arterial embolism and thrombosis",
"Asbestosis",
"Aseptic meningitis",
"Autoimmune hepatitis",
"Bacterial meningitis",
"Baker's cyst",
"Barrett's esophagus",
"Behcet's disease",
"Benign essential tremor",
"Berylliosis",
"Biliary colic",
"Bladder cancer",
"Bone metastasis",
"Botulism",
"Brain abscess",
"Brain metastasis",
"Breast cancer",
"Brucellosis",
"Budd-Chiari syndrome",
"Bulimia nervosa",
"Burn injury",
"Campylobacter infection",
"Cardiac tamponade",
"Carotid artery stenosis",
"Cauda equina syndrome",
"Celiac disease",
"Cervical spondylosis",
"Chagas disease",
"Cholangiocarcinoma",
"Cholangitis",
"Chronic bronchitis",
"Chronic cholecystitis",
"Chronic fatigue syndrome",
"Chronic glomerulonephritis",
"Chronic interstitial nephritis",
"Chronic liver failure",
"Chronic mesenteric ischemia",
"Chronic pancreatitis",
"Chronic subdural hematoma",
"Cirrhosis of liver",
"Clostridium difficile infection",
"Coarctation of aorta",
"Colorectal cancer",
"Complex regional pain syndrome",
"Compression fracture",
"Concussion",
"Congenital heart disease",
"Cushing's syndrome",
"Cyclic vomiting syndrome",
"Dacryocystitis",
"Dengue fever",
"Diabetic ketoacidosis",
"Diabetic nephropathy",
"Diabetic retinopathy",
"Diffuse idiopathic skeletal hyperostosis",
"Dilated cardiomyopathy",
"Disseminated intravascular coagulation",
"Drug-induced liver injury",
"Dumping syndrome",
"Duodenal ulcer",
"Ebola virus disease",
"Eclampsia",
"Ectopic pregnancy",
"Emphysema",
"Encephalitis",
"Enterocolitis",
"Eosinophilic esophagitis",
"Erythema multiforme",
"Esophageal cancer",
"Essential thrombocythemia",
" Ewing sarcoma",
"Factor V Leiden thrombophilia",
"Falls",
"Fat embolism syndrome",
"Felty's syndrome",
"Fetal alcohol syndrome",
"Fifth disease",
"Food poisoning",
"Fracture of femur",
"Fracture of hip",
"Fracture of humerus",
"Fracture of radius and ulna",
"Fracture of tibia and fibula",
"Frozen shoulder",
"Gastric cancer",
"Gastric ulcer",
"Gastritis",
"Gestational diabetes",
"Giant cell arteritis",
"Gilbert's syndrome",
"Guillain-Barré syndrome",
"Hantavirus pulmonary syndrome",
"Heart valve disease",
"Heat stroke",
"Hemolytic anemia",
"Hemolytic uremic syndrome",
"Henoch-Schönlein purpura",
"Hepatitis A",
"Hepatitis B",
"Hepatitis C",
"Hepatitis D",
"Hepatitis E",
"Hepatorenal syndrome",
"Hereditary hemochromatosis",
"Hodgkin's lymphoma",
"Human immunodeficiency virus infection",
"Huntington's disease",
"Hydrocephalus",
"Hypercalcemia",
"Hyperkalemia",
"Hypernatremia",
"Hyperparathyroidism",
"Hypocalcemia",
"Hypoglycemia",
"Hypokalemia",
"Hyponatremia",
"Hypoparathyroidism",
"Idiopathic pulmonary fibrosis",
"IgA nephropathy",
"Ileus",
"Infective endocarditis",
"Infertility",
"Inflammatory bowel disease",
"Intestinal obstruction",
"Intracerebral hemorrhage",
"Iron deficiency anemia",
"Ischemic colitis",
"Kawasaki disease",
"Kidney cancer",
"Kidney stones",
"Klinefelter syndrome",
"Lactose intolerance",
"Lead poisoning",
"Legionnaires' disease",
"Leukemia",
"Liver cancer",
"Lung cancer",
"Lyme disease",
"Lymphoma",
"Malaria",
"Malnutrition",
"Marfan syndrome",
"Measles",
"Medullary thyroid cancer",
"Melena",
"Meningioma",
"Meningitis",
"Mesothelioma",
"Metabolic acidosis",
"Metabolic alkalosis",
"Metastatic cancer",
"Middle East respiratory syndrome",
"Mitral regurgitation",
"Mixed connective tissue disease",
"Mononucleosis",
"Motor neuron disease",
"Mumps",
"Multiple myeloma",
"Myelodysplastic syndrome",
"Myocarditis",
"Narcolepsy",
"Nephrotic syndrome",
"Neuroblastoma",
"Neurofibromatosis",
"Nonalcoholic fatty liver disease",
"Non-Hodgkin lymphoma",
"Obstructive sleep apnea",
"Oliguria",
"Oral cancer",
"Osteomyelitis",
"Osteonecrosis",
"Ovarian cancer",
"Paget's disease of the nipple",
"Pancreatic cancer",
"Paralytic ileus",
"Parathyroid adenoma",
"Pelvic inflammatory disease",
"Pernicious anemia",
"Pheochromocytoma",
"Pinworm infection",
"Pituitary adenoma",
"Placenta previa",
"Polyarteritis nodosa",
"Polycystic kidney disease",
"Polycythemia vera",
"Polymyositis",
"Portal hypertension",
"Postoperative ileus",
"Preeclampsia",
"Primary biliary cholangitis",
"Primary hyperaldosteronism",
"Primary sclerosing cholangitis",
"Progressive supranuclear palsy",
"Prostate cancer",
"Pseudomembranous colitis",
"Pulmonary fibrosis",
"Pulmonary hypertension",
"Pyoderma gangrenosum",
"Rabies",
"Reactive arthritis",
"Reflux esophagitis",
"Renal artery stenosis",
"Renal cell carcinoma",
"Respiratory acidosis",
"Respiratory alkalosis",
"Retinoblastoma",
"Reye's syndrome",
"Rocky Mountain spotted fever",
"Rubella",
"Salmonella infection",
"Sarcoma",
"Scarlet fever",
"Sepsis",
"Severe acute respiratory syndrome",
"Sickle cell anemia",
"Silicosis",
"Small bowel obstruction",
"Small cell lung cancer",
"Spinal cord injury",
"Splenic rupture",
"Squamous cell carcinoma",
"Status epilepticus",
"Stevens-Johnson syndrome",
"Still's disease",
"Subarachnoid hemorrhage",
"Subdural hematoma",
"Superior vena cava syndrome",
"Systemic lupus erythematosus",
"Systemic sclerosis",
"Takayasu's arteritis",
"Temporal lobe epilepsy",
"Testicular cancer",
"Tetanus",
"Thalassemia",
"Thrombotic thrombocytopenic purpura",
"Thyroid cancer",
"Thyroiditis",
"Toxic epidermal necrolysis",
"Toxic megacolon",
"Transient ischemic attack",
"Traumatic brain injury",
"Trichinosis",
"Tuberculosis",
"Turner syndrome",
"Typhoid fever",
"Uremia",
"Uterine cancer",
"Uterine fibroids",
"Vaginal cancer",
"Varicella",
"Vasovagal syncope",
"Ventricular fibrillation",
"Ventricular tachycardia",
"Viral meningitis",
"Von Willebrand disease",
"Waldenström macroglobulinemia",
"Wegener's granulomatosis",
"Wilson's disease",
"Yellow fever",
"Zika virus disease",
"Aarskog-Scott syndrome",
"Abetalipoproteinemia",
"Acanthosis nigricans",
"Acid maltase deficiency",
"Acrocyanosis",
"Acrodynia",
"Acrokeratosis verruciformis of Hopf",
"Acute intermittent porphyria",
"Adrenoleukodystrophy",
"Agammaglobulinemia",
"Alagille syndrome",
"Albinism",
"Alexander disease",
"Alkaptonuria",
"Alpha-1 antitrypsin deficiency",
"Alport syndrome",
"Amelogenesis imperfecta",
"Androgen insensitivity syndrome",
"Angelman syndrome",
"Antiphospholipid syndrome",
"Arachnodactyly",
"Arnold-Chiari malformation",
"Arteriohepatic dysplasia",
"Ataxia-telangiectasia",
"Batten disease",
"Becker muscular dystrophy",
"Bloom syndrome",
"Blue rubber bleb nevus syndrome",
"Brittle bone disease",
"Brown-Séquard syndrome",
"Bulbar palsy",
"Canavan disease",
"Carney complex",
"Celiac sprue",
"Cerebral palsy",
"Charcot-Marie-Tooth disease",
"Chédiak-Higashi syndrome",
"Christmas disease",
"Chronic mucocutaneous candidiasis",
"Cockayne syndrome",
"Coffin-Lowry syndrome",
"Congenital adrenal hyperplasia",
"Congenital hypothyroidism",
"Cornelia de Lange syndrome",
"Craniosynostosis",
"Cri du chat syndrome",
"Crouzon syndrome",
"Cushing's disease",
"Cystic fibrosis",
"Darier's disease",
"Dejerine-Sottas disease",
"Dentatorubral-pallidoluysian atrophy",
"Dermatomyositis",
"Diamond-Blackfan anemia",
"DiGeorge syndrome",
"Down syndrome",
"Duchenne muscular dystrophy",
"Dysautonomia",
"Dyskeratosis congenita",
"Ehlers-Danlos syndrome",
"Ellis-van Creveld syndrome",
"Empty sella syndrome",
"Epidermolysis bullosa",
"Fabry disease",
"Familial adenomatous polyposis",
"Familial hypercholesterolemia",
"Fanconi anemia",
"Farber disease",
"Fetal hydantoin syndrome",
"Fragile X syndrome",
"Friedreich's ataxia",
"Fucosidosis",
"Galactosemia",
"Gardner syndrome",
"Gaucher disease",
"Gerstmann-Sträussler-Scheinker syndrome",
"Glycogen storage disease",
"Goodpasture syndrome",
"Gorlin syndrome",
"Gower's sign",
"Granulomatosis with polyangiitis",
"Graves' disease",
"Greig cephalopolysyndactyly syndrome",
"Guillain-Barré syndrome variants",
"Haim-Munk syndrome",
"Hartnup disease",
"Hay-Wells syndrome",
"Hemophilia A",
"Hemophilia B",
"Hereditary angioedema",
"Hereditary spherocytosis",
"Hirschsprung's disease",
"Histiocytosis X",
"Holt-Oram syndrome",
"Homocystinuria",
"Hunter syndrome",
"Hurler syndrome",
"Hyper IgE syndrome",
"Hyperkalemic periodic paralysis",
"Hypochondroplasia",
"Hypophosphatasia",
"Hypophosphatemic rickets",
"Ichthyosis vulgaris",
"Idiopathic thrombocytopenic purpura",
"Immune thrombocytopenia",
"Incontinentia pigmenti",
"Joubert syndrome",
"Kabuki syndrome",
"Kartagener syndrome",
"Kennedy's disease",
"Klippel-Feil syndrome",
"Klippel-Trenaunay syndrome",
"Krabbe disease",
"Lafora disease",
"Lambert-Eaton myasthenic syndrome",
"Landau-Kleffner syndrome",
"Laurence-Moon-Bardet-syndrome",
"Leber's hereditary optic neuropathy",
"Lesch-Nyhan syndrome",
"Leukodystrophy",
"Liddle syndrome",
"Li-Fraumeni syndrome",
"Loeys-Dietz syndrome",
"Long QT syndrome",
"Louis-Bar syndrome",
"Lowry-Maclean syndrome",
"Lujan-Fryns syndrome",
"Lysosomal storage disease",
"Machado-Joseph disease",
"Maple syrup urine disease",
"Maroteaux-Lamy syndrome",
"McCune-Albright syndrome",
"Meckel-Gruber syndrome",
"MELAS syndrome",
"MERRF syndrome",
"Metachromatic leukodystrophy",
"Microcephaly",
"Miller syndrome",
"Mitochondrial encephalomyopathy",
"Moebius syndrome",
"Morquio syndrome",
"Mowat-Wilson syndrome",
"Mucolipidosis",
"Mucopolysaccharidosis",
"Multiple endocrine neoplasia",
"Myotonic dystrophy",
"Nager syndrome",
"Nail-patella syndrome",
"Niemann-Pick disease",
"Noonan syndrome",
"Norrie disease",
"Oculocutaneous albinism",
"Ollier disease",
"Oral-facial-digital syndrome",
"Ornithine transcarbamylase deficiency",
"Osler-Weber-Rendu syndrome",
"Osteogenesis imperfecta",
"Osteopetrosis",
"Pallister-Hall syndrome",
"Parkinsonism-dementia complex of Guam",
"Parry-Romberg syndrome",
"Patau syndrome",
"Pelizaeus-Merzbacher disease",
"Pendred syndrome",
"Peutz-Jeghers syndrome",
"Pierre Robin sequence",
"Poland syndrome",
"Pompe disease",
"Prader-Willi syndrome",
"Primary ciliary dyskinesia",
"Progressive familial intrahepatic cholestasis",
"Propionic acidemia",
"Proteus syndrome",
"Pseudohypoparathyroidism",
"Pyruvate kinase deficiency",
"Refsum disease",
"Reiter's syndrome",
"Rett syndrome",
"Rhabdomyosarcoma",
"Richner-Hanhart syndrome",
"Roberts syndrome",
"Rothmund-Thomson syndrome",
"Rubinstein-Taybi syndrome",
"Sanfilippo syndrome",
"Schnyder corneal dystrophy",
"Seckel syndrome",
"Severe combined immunodeficiency",
"Shwachman-Diamond syndrome",
"Silver-Russell syndrome",
"Smith-Lemli-Opitz syndrome",
"Sotos syndrome",
"Spinal muscular atrophy",
"Stickler syndrome",
"Sturge-Weber syndrome",
"Subacute sclerosing panencephalitis",
"Sulfite oxidase deficiency",
"Swyer syndrome",
"Tangier disease",
"Tar syndrome",
"Tay-Sachs disease",
"Tetralogy of Fallot with pulmonary atresia",
"Thrombocytopenia-absent radius syndrome",
"Timothy syndrome",
"Tourette syndrome",
"Treacher Collins syndrome",
"Trisomy 13",
"Trisomy 18",
"Tuberous sclerosis",
"Usher syndrome",
"Van der Woude syndrome",
"Velo-cardio-facial syndrome",
"Vogt-Koyanagi-Harada disease",
"Waardenburg syndrome",
"Werdnig-Hoffmann disease",
"Acanthamoeba keratitis",
"Acute disseminated encephalomyelitis",
"Adenovirus infection",
"African sleeping sickness",
"Amebic dysentery",
"Anaplasmosis",
"Anthrax",
"Arboviral encephalitis",
"Ascariasis",
"Babesiosis",
"Bacillary angiomatosis",
"Balantidiasis",
"Bartonellosis",
"Blastomycosis",
"Bordetella pertussis infection",
"Borrelia recurrentis infection",
"Brucellosis",
"Burkholderia cepacia complex infection",
"Burkholderia mallei infection",
"Burkholderia pseudomallei infection",
"Candidemia",
"Cat-scratch disease",
"Chancroid",
"Chlamydia trachomatis infection",
"Cholera",
"Chromoblastomycosis",
"Clonorchiasis",
"Coccidioidomycosis",
"Colorado tick fever",
"Cryptococcosis",
"Cryptosporidiosis",
"Cutaneous larva migrans",
"Cysticercosis",
"Cytomegalovirus infection",
"Diphtheria",
"Dracunculiasis",
"Ehrlichiosis",
"Enterobiasis",
"Epstein-Barr virus infection",
"Fascioliasis",
"Fasciolopsiasis",
"Filariasis",
"Fusobacterium infection",
"Giardiasis",
"Glanders",
"Gonorrhea",
"Granuloma inguinale",
"Haemophilus influenzae infection",
"Hand, foot, and mouth disease",
"Hantavirus hemorrhagic fever with renal syndrome",
"Helicobacter pylori infection",
"Herpangina",
"Histoplasmosis",
"Hookworm infection",
"Human bocavirus infection",
"Human herpesvirus 6 infection",
"Human metapneumovirus infection",
"Human papillomavirus infection",
"Impetigo contagiosa",
"Infectious mononucleosis",
" Invasive aspergillosis",
" Invasive candidiasis",
" Invasive mucormycosis",
" Japanese encephalitis",
" Kala-azar",
" Keratoconjunctivitis sicca",
" Klebsiella pneumoniae infection",
" Leprosy",
" Leptospirosis",
" Listeriosis",
" Loiasis",
" Lymphogranuloma venereum",
" Maduromycosis",
" Marburg hemorrhagic fever",
" Measles",
" Melioidosis",
" Meningococcal disease",
" Microsporidiosis",
" Monkeypox",
" Mumps",
" Mycoplasma pneumoniae infection",
" Mycetoma",
" Necrotizing fasciitis",
" Neonatal herpes",
" Norovirus infection",
" Onchocerciasis",
" Oral candidiasis",
" Ornithosis",
" Paracoccidioidomycosis",
" Paragonimiasis",
" Pasteurella multocida infection",
" Pediculosis capitis",
" Pediculosis corporis",
" Pediculosis pubis",
" Pertussis",
" Plague",
" Pneumococcal disease",
" Pneumocystis pneumonia",
" Poliomyelitis",
" Primary amebic meningoencephalitis",
" Progressive multifocal leukoencephalopathy",
" Psittacosis",
" Q fever",
" Rabies",
" Relapsing fever",
" Respiratory syncytial virus infection",
" Rhinoscleroma",
" Rhinovirus infection",
" Ringworm",
" Rocky Mountain spotted fever",
" Rotavirus infection",
" Rubella",
" Salmonellosis",
" Scabies",
" Schistosomiasis",
" Scrub typhus",
" Severe acute respiratory syndrome coronavirus 2 infection",
" Shigellosis",
" Smallpox",
" Sporotrichosis",
" Staphylococcal food poisoning",
" Staphylococcal toxic shock syndrome",
" Streptococcus pneumoniae infection",
" Streptococcal pharyngitis",
" Strongyloidiasis",
" Syphilis",
" Taeniasis",
" Tetanus",
" Tinea barbae",
" Tinea capitis",
" Tinea cruris",
" Tinea manuum",
" Tinea nigra",
" Tinea pedis",
" Tinea unguium",
" Toxocariasis",
" Toxoplasmosis",
" Trachoma",
" Trichinellosis",
" Trichomoniasis",
" Trichuriasis",
" Trypanosomiasis",
" Tularemia",
" Typhoid fever",
" Typhus",
" Ureaplasma urealyticum infection",
" Varicella-zoster virus infection",
" Venezuelan equine encephalitis",
" Vibrio cholerae infection",
" Viral hemorrhagic fever",
" Viral meningitis",
" West Nile fever",
" Whooping cough",
" Yersinia enterocolitica infection",
" Yersinia pestis infection",
" Zoster",
"Abdominal compartment syndrome",
"Acalculous biliary pain",
"Acetaminophen toxicity",
"Acute fatty liver",
"Acute mesenteric ischemia",
"Acute mountain sickness",
"Acute tubular necrosis",
"Air embolism",
"Alcohol withdrawal syndrome",
"Allergic bronchopulmonary aspergillosis",
"Amniotic fluid embolism",
"Anterior cord syndrome",
"Aortitis",
"Aplastic crisis",
"ARDS due to sepsis",
"Aspiration pneumonia",
"Autonomic hyperreflexia",
"Bartholin's cyst abscess",
"Biliary dyskinesia",
"Blunt cardiac injury",
"Bronchiolitis obliterans organizing pneumonia",
"Brown-Séquard syndrome",
"Budd-Chiari syndrome",
"Burn wound infection",
"Calcium pyrophosphate deposition disease",
"Cardiac amyloidosis",
"Cardiogenic shock",
"Central cord syndrome",
"Cerebral edema",
"Cervical radiculopathy",
"Cholestasis of pregnancy",
"Chronic mesenteric ischemia",
"Compartment syndrome",
"Complete heart block",
"Cor pulmonale",
"Cricothyroiditis",
"Cushing's reflex",
"Delayed gastric emptying",
"Diabetic foot ulcer",
"Disseminated intravascular coagulation due to sepsis",
"Drug-induced Stevens-Johnson syndrome",
"Eclampsia",
"Electrical injury",
"Erythema nodosum",
"Esophageal perforation",
"Extrinsic allergic alveolitis",
"Febrile neutropenia",
"Flash pulmonary edema",
"Gastric volvulus",
"Hepatic encephalopathy",
"Hepatorenal syndrome",
"Hyperosmolar hyperglycemic state",
"Hypersensitivity pneumonitis",
"Hypovolemic shock",
"Increased intracranial pressure",
"Infected pancreatic pseudocyst",
"Intestinal perforation",
"Intra-abdominal abscess",
"Ischemic hepatitis",
"Keratoacanthoma",
"Lactic acidosis",
"Lumbar spinal stenosis",
"Malignant hyperthermia",
"Massive hemoptysis",
"Mediastinitis",
"Metabolic encephalopathy",
"Multifocal motor neuropathy",
"Neurogenic shock",
"Nonketotic hyperosmolar coma",
"Obstructive uropathy",
"Ogilvie syndrome",
"Pancreatic abscess",
"Paraneoplastic syndrome",
"Peritonitis",
"Phlegmasia cerulea dolens",
"Posterior reversible encephalopathy syndrome",
"Postoperative fever",
"Postpartum endometritis",
"Pre-eclampsia",
"Primary graft dysfunction",
"Pseudomembranous colitis due to Clostridium difficile",
"Pulmonary contusion",
"Pulmonary edema due to heart failure",
"Rectal prolapse",
"Refeeding syndrome",
"Rhabdomyolysis",
"Ruptured ectopic pregnancy",
"Sclerosing peritonitis",
"Septic arthritis",
"Septic shock",
"Serotonin syndrome",
"Severe sepsis",
"Small intestinal bacterial overgrowth",
"Spontaneous bacterial peritonitis",
"Spontaneous pneumothorax",
"Status asthmaticus",
"Superior vena cava obstruction",
"Syndrome of inappropriate antidiuretic hormone secretion",
"Tension pneumothorax",
"Thyroid storm",
"Torsades de pointes",
"Transfusion reaction",
"Traumatic pneumothorax",
"Uremic encephalopathy",
"Uterine inversion",
"Ventricular aneurysm",
"Volvulus",
"Waterhouse-Friderichsen syndrome",
"Wernicke encephalopathy",
"Acute rheumatic fever",
"Ankylosing spondylitis with uveitis",
"Antiphospholipid antibody syndrome",
"Behcet's disease with neurological involvement",
"Churg-Strauss syndrome with cardiac involvement",
"Dermatomyositis with pulmonary involvement",
"Goodpasture's syndrome with pulmonary hemorrhage",
"Granulomatosis with polyangiitis with renal involvement",
"Juvenile dermatomyositis",
"Lupus nephritis",
"Mixed connective tissue disease with pulmonary hypertension",
"Polymyositis with dysphagia",
"Reactive arthritis with sacroiliitis",
"Relapsing polychondritis with airway involvement",
"Rheumatoid arthritis with vasculitis",
"Scleroderma with interstitial lung disease",
"Sjögren's syndrome with lymphoma",
"Systemic lupus erythematosus with central nervous system involvement",
"Undifferentiated connective tissue disease",
"Vasculitis with peripheral neuropathy",
"Acute cerebellar ataxia",
"Acute flaccid myelitis",
"Amyotrophic lateral sclerosis with frontotemporal dementia",
"Benign intracranial hypertension",
"Central pontine myelinolysis",
"Cerebellar degeneration",
"Chronic inflammatory demyelinating polyneuropathy",
"Complex regional pain syndrome type 1",
"Complex regional pain syndrome type 2",
"Cranial nerve palsy",
"Diabetic neuropathy with autonomic dysfunction",
"Essential tremor with cognitive impairment",
"Guillain-Barré syndrome with cranial nerve involvement",
"Lambert-Eaton myasthenic syndrome with small cell lung cancer",
"Multifocal motor neuropathy with conduction block",
"Multiple sclerosis with optic neuritis",
"Myasthenia gravis with thymoma",
"Paraneoplastic cerebellar degeneration",
"Paraneoplastic encephalomyelitis",
"Parkinson's disease with dementia",
"Peripheral neuropathy due to chemotherapy",
"Posterior cortical atrophy",
"Primary lateral sclerosis",
"Progressive bulbar palsy",
"Progressive supranuclear palsy with falls",
"Restless legs syndrome with periodic limb movements of sleep",
"Spinal cord compression",
"Subacute combined degeneration of spinal cord",
"Transverse myelitis",
"Trigeminal neuralgia with atypical facial pain",
"Adrenal crisis",
"Central diabetes insipidus",
"Congenital adrenal hyperplasia with salt-wasting",
"Empty sella syndrome with pituitary dysfunction",
"Gestational transient thyrotoxicosis",
"Hyperaldosteronism due to adrenal adenoma",
"Hypercalcemic crisis",
"Hyperthyroidism due to Graves' disease",
"Hypoglycemic unawareness",
"Hypopituitarism due to pituitary tumor",
"Hypothyroidism due to Hashimoto's thyroiditis",
"Myxedema coma",
"Nephrogenic diabetes insipidus",
"Pheochromocytoma crisis",
"Primary hyperparathyroidism with hypercalcemia",
"Secondary adrenal insufficiency",
"Sheehan's syndrome",
"Syndrome of inappropriate antidiuretic hormone secretion due to small cell lung cancer",
"Thyroid storm due to untreated hyperthyroidism",
"Waterhouse-Friderichsen syndrome due to meningococcal sepsis",
"Acute angle-closure glaucoma",
"Anterior ischemic optic neuropathy",
"Branch retinal artery occlusion",
"Branch retinal vein occlusion",
"Central retinal artery occlusion",
"Central retinal vein occlusion",
"Diabetic macular edema",
"Giant cell arteritis with vision loss",
"Idiopathic intracranial hypertension with papilledema",
"Keratoconus with corneal hydrops",
"Macular hole",
"Posterior ischemic optic neuropathy",
"Primary open-angle glaucoma with visual field loss",
"Retinal detachment with macular involvement",
"Retinitis pigmentosa with central vision loss",
"Uveitis with secondary glaucoma",
"Vitreous hemorrhage",
"Age-related macular degeneration with choroidal neovascularization",
"Allergic fungal sinusitis",
"Barotrauma of the ear",
"Benign paroxysmal positional vertigo",
"Cholesteatoma with complications",
"Chronic suppurative otitis media",
"Labyrinthitis",
"Malignant otitis externa",
"Meniere's disease with drop attacks",
"Perforated tympanic membrane with infection",
"Sudden sensorineural hearing loss",
"Tympanosclerosis",
"Vestibular neuronitis",
"Aortoesophageal fistula",
"Boerhaave syndrome",
"Esophageal stricture with dysphagia",
"Gastric outlet obstruction",
"Hepatic hydrothorax",
"Hepatic vein thrombosis",
"Infective esophagitis",
"Intussusception",
"Large bowel obstruction",
"Mallory-Weiss tear with hematemesis",
"Mesenteric venous thrombosis",
"Ogilvie's syndrome with colonic perforation",
"Pancreatic pseudocyst rupture",
"Primary sclerosing cholangitis with biliary strictures",
"Small bowel volvulus",
"Spontaneous esophageal rupture",
"Upper gastrointestinal hemorrhage due to varices",
"Acute kidney injury due to rhabdomyolysis",
"Acute poststreptococcal glomerulonephritis",
"Alport syndrome with end-stage renal disease",
"Antiglomerular basement membrane disease",
"Chronic kidney disease with hyperparathyroidism",
"Focal segmental glomerulosclerosis with nephrotic syndrome",
"Hemolytic uremic syndrome with renal failure",
"IgA nephropathy with macroscopic hematuria",
"Membranoproliferative glomerulonephritis",
"Membranous nephropathy with thromboembolism",
"Minimal change disease with nephrotic syndrome",
"Polycystic kidney disease with liver cysts",
"Renal artery stenosis with renovascular hypertension",
"Renal tubular acidosis",
"Systemic lupus erythematosus with lupus nephritis class IV",
"Thrombotic microangiopathy with acute kidney injury",
"Ureteropelvic junction obstruction with hydronephrosis",
"Vesicoureteral reflux with recurrent urinary tract infections",
"Anorectal fistula",
"Clostridium difficile colitis with toxic megacolon",
"Colorectal cancer with metastasis",
"Crohn's disease with fistula formation",
"Diverticular abscess",
"Hirschsprung's disease with enterocolitis",
"Inflammatory bowel disease with extraintestinal manifestations",
"Irritable bowel syndrome with severe abdominal pain",
"Microscopic colitis with chronic diarrhea",
"Pouchitis after ileal pouch-anal anastomosis",
"Primary sclerosing cholangitis with dominant stricture",
"Pseudomembranous colitis with perforation",
"Short bowel syndrome with malabsorption",
"Ulcerative colitis with pancolitis",
"Volvulus of the sigmoid colon",
"Avascular necrosis of the hip",
"Carpal tunnel syndrome with thenar atrophy",
"Degenerative disc disease with radiculopathy",
"Dupuytren's contracture with finger flexion deformity",
"Lateral epicondylitis with pain at rest",
"Medial epicondylitis with paresthesia",
"Morton's neuroma with chronic foot pain",
"Osteoarthritis of the knee with joint effusion",
"Plantar fasciitis with heel spur",
"Posterior tibial tendon dysfunction with flatfoot deformity",
"Rotator cuff tear with limited range of motion",
"Spinal stenosis with neurogenic claudication",
"Thoracic outlet syndrome with vascular compression",
"Trigger finger with locking",
"Ulnar nerve entrapment at the elbow",
"Adhesive capsulitis with severe pain and stiffness",
"Ankylosing spondylitis with spinal fusion",
"Gout with tophi formation",
"Osteoporosis with vertebral compression fracture",
"Polymyalgia rheumatica with giant cell arteritis",
"Rheumatoid arthritis with joint destruction",
"Systemic lupus erythematosus with arthritis and organ involvement",
"Acute lymphoblastic leukemia with central nervous system involvement",
"Acute myeloid leukemia with disseminated intravascular coagulation",
"Chronic lymphocytic leukemia with Richter's transformation",
"Chronic myeloid leukemia in blast crisis",
"Hodgkin lymphoma with B symptoms",
"Multiple myeloma with hypercalcemia",
"Non-Hodgkin lymphoma with bulky disease",
"Primary myelofibrosis with splenomegaly",
"Waldenström macroglobulinemia with hyperviscosity syndrome",
"Aplastic anemia with severe pancytopenia",
"Disseminated intravascular coagulation due to malignancy",
"Essential thrombocythemia with thrombotic complications",
"Hemolytic anemia due to autoimmune disease",
"Hereditary spherocytosis with gallstones",
"Idiopathic thrombocytopenic purpura with bleeding",
"Myelodysplastic syndrome with progression to leukemia",
"Polycythemia vera with erythrocytosis and thrombosis",
"Sickle cell disease with vaso-occlusive crisis",
"Thalassemia major with transfusion dependence",
"Aortic dissection type A",
"Cardiogenic shock due to acute myocardial infarction",
"Complete heart block with syncope",
"Dilated cardiomyopathy with severe heart failure",
"Hypertrophic cardiomyopathy with outflow obstruction",
"Infective endocarditis with valvular vegetation",
"Left ventricular aneurysm with thromboembolism",
"Mitral stenosis with pulmonary hypertension",
"Pericardial effusion with tamponade",
"Pulmonary embolism with right heart strain",
"Restrictive cardiomyopathy with diastolic dysfunction",
"Severe aortic stenosis with heart failure symptoms",
"Severe mitral regurgitation with left ventricular dysfunction",
"Unstable angina with high-risk features",
"Ventricular tachycardia with hemodynamic instability",
"Wolff-Parkinson-White syndrome with atrial fibrillation",
"Acute respiratory distress syndrome due to pneumonia",
"Allergic bronchopulmonary aspergillosis with bronchiectasis",
"Asthma exacerbation with respiratory failure",
"Bronchiolitis obliterans with progressive airflow obstruction",
"Chronic obstructive pulmonary disease exacerbation with hypercapnia",
"Cystic fibrosis with pulmonary exacerbation",
"Hypersensitivity pneumonitis with fibrosis"
]

const giveRandomDisease = () => {

  if (!Array.isArray(arrayofDisease) || arrayofDisease.length === 0) {
    return undefined; // Or throw an error: throw new Error("Input must be a non-empty array.");
  }
  const randomIndex = Math.floor(Math.random() * arrayofDisease.length);
  return arrayofDisease[randomIndex];
};

export default giveRandomDisease;
